name: Rustam Gaifullin
markdown: kramdown
theme: jekyll-theme-cayman
title: Rustam Gaifullin's blog
show_downloads: false

timezone: Europe/Warsaw

exclude: [Gemfile, Gemfile.lock, README.md]

google_analytics: UA-93980857-1
